In [1]:
import numpy as np

normal array

In [2]:
arr = [1,2,3,4,5]

numpy array

In [3]:
np.array(arr)

array([1, 2, 3, 4, 5])

In [4]:
arr2 = [[1,2,3],[2,3,4],[5,6,7]]
nparr = np.array(arr2)
nparr

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [5]:
np.arange(5,12,2)

array([ 5,  7,  9, 11])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros([3,4,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.ones([3,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
np.linspace(start=11, stop=20, num =10
)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
from numpy import random

In [12]:

random.randn()

-0.3030475211948589

In [13]:
narr= random.randint(1, 10, size=[2,3])
narr

array([[7, 5, 4],
       [6, 4, 9]], dtype=int32)

In [14]:
nrr2 = narr.reshape(3,2)

In [15]:
narr

array([[7, 5, 4],
       [6, 4, 9]], dtype=int32)

In [16]:
nrr2

array([[7, 5],
       [4, 6],
       [4, 9]], dtype=int32)

In [17]:
narr.max()


np.int32(9)

In [18]:
narr.argmax()

np.int64(5)

In [19]:
narr.min()

np.int32(4)

In [20]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2 = arr[5:8]
arr2

array([5, 6, 7])

In [23]:
arr2[2] = 100

In [24]:
arr2

array([  5,   6, 100])

In [25]:
arr

array([  0,   1,   2,   3,   4,   5,   6, 100,   8,   9])

In [26]:
arr2[:] = 200

In [27]:
arr2

array([200, 200, 200])

In [28]:
arr

array([  0,   1,   2,   3,   4, 200, 200, 200,   8,   9])

In [29]:
arr3 = arr[2:6].copy()
arr3

array([  2,   3,   4, 200])

In [30]:
arr3[:] = 300
arr3

array([300, 300, 300, 300])

In [37]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
matrix[1:, 1:3]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [33]:
third_row = matrix[2]
third_row

array([7, 8, 9])

In [46]:
arr = [200,3,4,6,5,100,7 , 300, 400, 500]
ans = []
for i in arr:
    if i > 5:
        ans.append(i)
ans

[200, 6, 100, 7, 300, 400, 500]

In [51]:
narr = np.array(arr)
bool_arr = narr > 5

In [52]:
narr[bool_arr]

array([200,   6, 100,   7, 300, 400, 500])

In [56]:
narr + narr

array([ 400,    6,    8,   12,   10,  200,   14,  600,  800, 1000])

In [58]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [62]:
arr2 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])